/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IconGithub: typeof import('./src/components/icons/IconGithub.vue')['default']
    IconInfo: typeof import('./src/components/icons/IconInfo.vue')['default']
    IconJuejin: typeof import('./src/components/icons/IconJuejin.vue')['default']
    IconMore: typeof import('./src/components/icons/IconMore.vue')['default']
    IconPic: typeof import('./src/components/icons/IconPic.vue')['default']
    IconRandom: typeof import('./src/components/icons/IconRandom.vue')['default']
    MyComment: typeof import('./src/components/MyComment.vue')['default']
    MyHeader: typeof import('./src/components/MyHeader.vue')['default']
    SkeletonTemplate: typeof import('./src/components/SkeletonTemplate.vue')['default']
  }
}
